Update release_manager.yml

diff --git a/.github/workflows/release_manager.yml b/.github/workflows/release_manager.yml
--- a/.github/workflows/release_manager.yml
+++ b/.github/workflows/release_manager.yml
@@ -28,44 +28,47 @@ jobs:
         echo "Get the changes before we merge"
         org_repo=${{ inputs.repo_name }}
         repo_name=$(echo ${org_repo} | cut -d/ -f2)
+                 
+        cd ~/git
+        if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
+          
+        gh auth login --with-token < ~/.gh_secrets
+          
+        echo "Cloing the repo"
+        git clone -b release "https://github.com/${org_repo}"
+          
+        cd ${repo_name}
+        echo "I am in ${repo_name}"
+          
+        echo "Checking out the PR"
+        gh pr checkout ${{ inputs.pr_number }}
+        changes=$(git diff release | grep ^+ | grep -v release.txt | sed 's/+//g')
+          
+        echo "+++++++++++++++++++++++++++++++++++++++++++++"
+        git diff release
+        echo "+++++++++++++++++++++++++++++++++++++++++++++"
+          
+        echo ${changes}
+  
+        echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+        echo ${changes_to_deploy}
         
-        echo "Repo name is ${{ inputs.repo_name }} and the PR number is ${{ inputs.pr_number }}"
-        URL="https://api.github.com/repos/${{ inputs.repo_name }}/pulls/${{ inputs.pr_number }}/files"
-        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
-               
-        if [[ $FILES == 'release.txt' ]]
-        then
-          echo "Release.txt modified, procedding further to deploy the code on puppet master..."
-          echo "file_name=$FILES" >> $GITHUB_OUTPUT
-          #echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
-          #echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
-          
-          cd ~/git
-          if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
-          
-          gh auth login --with-token < ~/.gh_secrets
-          
-          echo "Cloing the repo"
-          git clone -b release "https://github.com/${org_repo}"
-          
-          cd ${repo_name}
-          echo "I am in ${repo_name}"
-          
-          echo "Checking out the PR"
-          gh pr checkout ${{ inputs.pr_number }}
-          changes=$(git diff release | grep ^+ | grep -v release.txt | sed 's/+//g')
-          
-          echo "+++++++++++++++++++++++++++++++++++++++++++++"
-          git diff release
-          echo "+++++++++++++++++++++++++++++++++++++++++++++"
-          
-          echo ${changes}
-          #echo "::set-output name=changes_to_deploy::$(echo ${changes})"
-          echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
-          echo ${changes_to_deploy}
+        if: startsWith(inputs.repo_name, "${OWNER}/tb")
+          echo "Merging PR...."
+          gh pr merge --merge
+          if [ $? -ne 0 ]; then
+            echo ""
+            echo "PR Merger Failed!!"
+            gh auth logout --hostname github.com
+            echo ""
+            exit 1
+          else
+            echo ""
+            echo "PR Has Been Merged Successfully!!"
+            gh auth logout --hostname github.com
+          fi
         fi
     outputs:
-      file_name: ${{ steps.step1.outputs.file_name }}
       changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
       
   processing_release_manager_2:
@@ -82,150 +85,49 @@ jobs:
         echo "Get the changes before we merge"
         org_repo=${{ inputs.repo_name }}
         repo_name=$(echo ${org_repo} | cut -d/ -f2)
-        
-        echo "Repo name is ${{ inputs.repo_name }} and the PR number is ${{ inputs.pr_number }}"
-        URL="https://api.github.com/repos/${{ inputs.repo_name }}/pulls/${{ inputs.pr_number }}/files"
-        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
-               
-        if [[ $FILES == 'release.txt' ]]
-        then
-          echo "Release.txt modified, procedding further to deploy the code on puppet master..."
-          echo "file_name=$FILES" >> $GITHUB_OUTPUT
-          #echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
-          #echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
+                
+        cd ~/git
+        if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
           
-          cd ~/git
-          if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
+        gh auth login --with-token < ~/.gh_secrets
           
-          gh auth login --with-token < ~/.gh_secrets
+        echo "Cloing the repo"
+        git clone -b release "https://github.com/${org_repo}"
           
-          echo "Cloing the repo"
-          git clone -b release "https://github.com/${org_repo}"
+        cd ${repo_name}
+        echo "I am in ${repo_name}"
           
-          cd ${repo_name}
-          echo "I am in ${repo_name}"
+        echo "Checking out the PR"
+        gh pr checkout ${{ inputs.pr_number }}
+        changes=$(git diff release | grep ^+ | grep -v release.txt | sed 's/+//g')
           
-          echo "Checking out the PR"
-          gh pr checkout ${{ inputs.pr_number }}
-          changes=$(git diff release | grep ^+ | grep -v release.txt | sed 's/+//g')
+        echo "+++++++++++++++++++++++++++++++++++++++++++++"
+        git diff release
+        echo "+++++++++++++++++++++++++++++++++++++++++++++"
           
-          echo "+++++++++++++++++++++++++++++++++++++++++++++"
-          git diff release
-          echo "+++++++++++++++++++++++++++++++++++++++++++++"
-          
-          echo ${changes}
+        echo ${changes}
           #echo "::set-output name=changes_to_deploy::$(echo ${changes})"
-          echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
-          echo ${changes_to_deploy}
+        echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+        echo ${changes_to_deploy}
+        if: |
+          startsWith(inputs.repo_name, "${OWNER}/bt")
+          (!startsWith(inputs.repo_name, "${OWNER}/tb") && !startsWith(inputs.repo_name, "${OWNER}/bt"))
+          echo "Merging PR...."
+          gh pr merge --merge
+          if [ $? -ne 0 ]; then
+            echo ""
+            echo "PR Merger Failed!!"
+            gh auth logout --hostname github.com
+            echo ""
+            exit 1
+          else
+            echo ""
+            echo "PR Has Been Merged Successfully!!"
+            gh auth logout --hostname github.com
+          fi
         fi
     outputs:
-      file_name: ${{ steps.step1.outputs.file_name }}
       changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
-      
-  processing_release_manager_for_merge_tb:
-    if: |
-      startsWith(inputs.repo_name, "${OWNER}/tb")
-    name: collecting_release_version_for_merge_1
-    needs: processing_release_manager_1
-    runs-on: [ self-hosted, linux, tableau_runner ]
-    steps:
-    - id: step2
-      name: PR Approval and Merging 
-      run: |
-        #Setting UP Variables#
-        orgAndRepo=${{ inputs.repo_name }}
-        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
-        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
-        
-        echo "Printing Vars...."
-        echo "Org Name - $orgName"
-        echo "Repo Name - $repoName"
-        
-        #Execution Starts from here#
-        cd ~/git
-        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
-        gh auth login --with-token < ~/.gh_secrets
-        echo ""
-        echo "Checking the status of GH login...."
-        gh auth status
-        echo ""
-        
-        echo "Clonning the repository...."
-        git clone -b release "https://github.com/${orgAndRepo}"
-        echo ""
-        cd $repoName
-        echo "I am in $repoName"
-        echo ""
-        echo "Checking out the PR...."
-        gh pr checkout ${{ inputs.pr_number }}
-        echo ""
-        
-        echo "Merging PR...."
-        gh pr merge --merge
-        if [ $? -ne 0 ]; then
-          echo ""
-          echo "PR Merger Failed!!"
-          gh auth logout --hostname github.com
-          echo ""
-          exit 1
-        else
-          echo ""
-          echo "PR Has Been Merged Successfully!!"
-          gh auth logout --hostname github.com
-        fi
-        
-  processing_release_manager_for_merge_bt:
-    if: |
-      startsWith(inputs.repo_name, "${OWNER}/bt") ||
-      (!startsWith(inputs.repo_name, "${OWNER}/tb") && !startsWith(inputs.repo_name, "${OWNER}/bt"))
-    name: collecting_release_version_for_merge
-    needs: processing_release_manager_2
-    runs-on: [ self-hosted, linux, code_release ]
-    steps:
-    - id: step2
-      name: PR Approval and Merging 
-      run: |
-        #Setting UP Variables#
-        orgAndRepo=${{ inputs.repo_name }}
-        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
-        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
-        
-        echo "Printing Vars...."
-        echo "Org Name - $orgName"
-        echo "Repo Name - $repoName"
-        
-        #Execution Starts from here#
-        cd ~/git
-        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
-        gh auth login --with-token < ~/.gh_secrets
-        echo ""
-        echo "Checking the status of GH login...."
-        gh auth status
-        echo ""
-        
-        echo "Clonning the repository...."
-        git clone -b release "https://github.com/${orgAndRepo}"
-        echo ""
-        cd $repoName
-        echo "I am in $repoName"
-        echo ""
-        echo "Checking out the PR...."
-        gh pr checkout ${{ inputs.pr_number }}
-        echo ""
-        
-        echo "Merging PR...."
-        gh pr merge --merge
-        if [ $? -ne 0 ]; then
-          echo ""
-          echo "PR Merger Failed!!"
-          gh auth logout --hostname github.com
-          echo ""
-          exit 1
-        else
-          echo ""
-          echo "PR Has Been Merged Successfully!!"
-          gh auth logout --hostname github.com
-        fi
         
   processing_release_manager_actions_tableau_runner:
     if: |
@@ -244,6 +146,7 @@ jobs:
       with:
         repo_name: '${{ inputs.repo_name }}'
         pr_changes: ${{ matrix.list_of_changes }}
+        running_on: 'tableau'
  
   processing_release_manager_actions_bt_runner:
     if: | 
@@ -262,5 +165,4 @@ jobs:
       with:
         repo_name: '${{ inputs.repo_name }}'
         pr_changes: ${{ matrix.list_of_changes }}
-        
-  
+        running_on: 'bt'
