Update release_manager.yml

diff --git a/.github/workflows/release_manager.yml b/.github/workflows/release_manager.yml
--- a/.github/workflows/release_manager.yml
+++ b/.github/workflows/release_manager.yml
@@ -34,8 +34,8 @@ jobs:
         then
           echo "Release.txt modified, procedding further to deploy the code on puppet master..."
           echo "file_name=$FILES" >> $GITHUB_OUTPUT
-          echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
-          echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
+          #echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
+          #echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
           
           cd ~/git
           if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
@@ -64,8 +64,6 @@ jobs:
     outputs:
       file_name: ${{ steps.step1.outputs.file_name }}
       changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
-      reponame: ${{ steps.step1.outputs.Repo_Name }}
-      prnumber: ${{ steps.step1.outputs.PR_number }}
       
   processing_release_manager_2:
     if: |
@@ -90,8 +88,8 @@ jobs:
         then
           echo "Release.txt modified, procedding further to deploy the code on puppet master..."
           echo "file_name=$FILES" >> $GITHUB_OUTPUT
-          echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
-          echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
+          #echo "Repo_Name=${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
+          #echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
           
           cd ~/git
           if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
@@ -120,12 +118,64 @@ jobs:
     outputs:
       file_name: ${{ steps.step1.outputs.file_name }}
       changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
-      reponame: ${{ steps.step1.outputs.Repo_Name }}
-      prnumber: ${{ steps.step1.outputs.PR_number }}
       
-  processing_release_manager_for_merge:
+  processing_release_manager_for_merge_tb:
+    if: |
+      startsWith(inputs.repo_name, 'pcherukusfdc/tb')
+    name: collecting_release_version_for_merge_1
+    runs-on: [ self-hosted, linux, tableau_runner ]
+    steps:
+    - id: step2
+      name: PR Approval and Merging 
+      run: |
+        #Setting UP Variables#
+        orgAndRepo=${{ inputs.repo_name }}
+        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
+        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
+        
+        echo "Printing Vars...."
+        echo "Org Name - $orgName"
+        echo "Repo Name - $repoName"
+        
+        #Execution Starts from here#
+        cd ~/git
+        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
+        gh auth login --with-token < ~/.gh_secrets
+        echo ""
+        echo "Checking the status of GH login...."
+        gh auth status
+        echo ""
+        
+        echo "Clonning the repository...."
+        git clone -b release "https://github.com/${orgAndRepo}"
+        echo ""
+        cd $repoName
+        echo "I am in $repoName"
+        echo ""
+        echo "Checking out the PR...."
+        gh pr checkout ${{ inputs.pr_number }}
+        echo ""
+        
+        echo "Merging PR...."
+        gh pr merge --merge
+        if [ $? -ne 0 ]; then
+          echo ""
+          echo "PR Merger Failed!!"
+          gh auth logout --hostname github.com
+          echo ""
+          exit 1
+        else
+          echo ""
+          echo "PR Has Been Merged Successfully!!"
+          gh auth logout --hostname github.com
+        fi
+        
+  processing_release_manager_for_merge_bt:
+    if: |
+      startsWith(inputs.repo_name, 'pcherukusfdc/bt') ||
+      (!startsWith(inputs.repo_name, 'pcherukusfdc/tb') && !startsWith(inputs.repo_name, 'pcherukusfdc/bt'))
     name: collecting_release_version_for_merge
-    runs-on: [ self-hosted, linux, code_runner, tableau_runner ]
+    runs-on: [ self-hosted, linux, code_runner ]
     steps:
     - id: step2
       name: PR Approval and Merging 
