Update release_manager.yml

diff --git a/.github/workflows/release_manager.yml b/.github/workflows/release_manager.yml
--- a/.github/workflows/release_manager.yml
+++ b/.github/workflows/release_manager.yml
@@ -8,12 +8,12 @@ on:
         type: string
       pr_number:
         required: true
-        type: string
+        type: number
 
 jobs:
   processing_release_manager:
     name: collecting_release_version
-    runs-on: [ self-hosted, linux, code_release ]
+    runs-on: [ self-hosted, linux, puppet_release ]
     steps:
     - id: step1
       name: Checking which files changed 
@@ -23,38 +23,106 @@ jobs:
         org_repo=${{ inputs.repo_name }}
         repo_name=$(echo ${org_repo} | cut -d/ -f2)
         
+        echo "Repo name is ${{ inputs.repo_name }} and the PR number is ${{ inputs.pr_number }}"
+        URL="https://api.github.com/repos/${{ inputs.repo_name }}/pulls/${{ inputs.pr_number }}/files"
+        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
+               
+        if [[ $FILES == 'release.txt' ]]
+        then
+          echo "Release.txt modified, procedding further to deploy the code on puppet master..."
+          echo "file_name=$FILES" >> $GITHUB_OUTPUT
+          #echo "Repo_Name=$repo_name" >> $GITHUB_OUTPUT
+          #echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
+          
+          cd ~/git
+          if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
+          
+          gh auth login --with-token < ~/.gh_secrets
+          
+          echo "Cloing the repo"
+          git clone -b release "https://github.com/${org_repo}"
+          
+          cd ${repo_name}
+          echo "I am in ${repo_name}"
+          
+          echo "Checking out the PR"
+          gh pr checkout ${{ inputs.pr_number }}
+          changes=$(git diff main | grep ^+ | grep -v release.txt | sed 's/+//g')
+          
+          echo "+++++++++++++++++++++++++++++++++++++++++++++"
+          git diff main
+          echo "+++++++++++++++++++++++++++++++++++++++++++++"
+          
+          echo ${changes}
+          #echo "::set-output name=changes_to_deploy::$(echo ${changes})"
+          echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
+          echo ${changes_to_deploy}
+        fi
+    - id: step2
+      name: PR Approval and Merging
+      if: ${{ success() && steps.step1.outputs.file_name == 'release.txt' }} 
+      run: |
+        #Setting UP Variables#
+        orgAndRepo=${{ inputs.repo_name }}
+        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
+        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
+        
+        echo "Printing Vars...."
+        echo "Org Name - $orgName"
+        echo "Repo Name - $repoName"
+        
+        #Execution Starts from here#
         cd ~/git
-        if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
-          
+        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
         gh auth login --with-token < ~/.gh_secrets
-          
-        echo "Cloing the repo"
-        git clone -b release "https://github.com/${org_repo}"
+        echo ""
+        echo "Checking the status of GH login...."
+        gh auth status
+        echo ""
         
-        cd ${repo_name}
-        echo "I am in ${repo_name}"
+        echo "Clonning the repository...."
+        git clone -b release "https://github.com/${orgAndRepo}"
+        echo ""
+        cd $repoName
+        echo "I am in $repoName"
+        echo ""
+        echo "Checking out the PR...."
+        gh pr checkout ${{ inputs.pr_number }}
+        echo ""
         
-        changes=$(git show refs/heads/release | grep -v release | grep ^+ | sed 's/+//g')
-        echo ${changes}
-        echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
-        echo ${changes_to_deploy}
-        
+        echo "Merging PR...."
+        gh pr merge --merge
+        if [ $? -ne 0 ]; then
+          echo ""
+          echo "PR Merger Failed!!"
+          gh auth logout --hostname github.com
+          echo ""
+          exit 1
+        else
+          echo ""
+          echo "PR Has Been Merged Successfully!!"
+          gh auth logout --hostname github.com
+        fi
     outputs:
+      file_name: ${{ steps.step1.outputs.file_name }}
       changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
-
+      #REPO_name: ${{ steps.step1.outputs.REPO_name }}
+      #PR_Number: ${{ steps.step1.outputs.PR_number }}
       
   processing_release_manager2:
     needs: processing_release_manager
-    #if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
-    runs-on: [ self-hosted, linux, code_release ]
+    if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
+    runs-on: [ self-hosted, linux, puppet_release ]
     strategy:
       matrix:
         list_of_changes: ${{ fromJSON(needs.processing_release_manager.outputs.changes_from_pr) }}
     steps:
     - id: step3
       name: call actions
-      #if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
+      if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
       uses: pcherukusfdc/release_manager@main
       with:
         repo_name: '${{ inputs.repo_name }}'
+        pr_num: '${{ inputs.pr_number }}'
+        #pr_changes: ${{ needs.processing_release_manager.outputs.changes_from_pr }}
         pr_changes: ${{ matrix.list_of_changes }}
